### ISSUE TITLE
error popup in endless loop

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.rcp#1012]
while playing with WCF i encountered this:
the problem is, that there is no way to close the error-dialog

![grafik](https://user-images.githubusercontent.com/41451972/141973841-216ee78d-e135-4cb9-9c3f-517d45b81d9b.png)

java.lang.NullPointerException: Cannot invoke "aero.minova.rcp.rcp.accessor.DetailAccessor.setSelectedControl(org.eclipse.swt.widgets.Control)" because the return value of "aero.minova.rcp.model.form.MDetail.getDetailAccessor()" is null
Cannot invoke "aero.minova.rcp.rcp.accessor.DetailAccessor.setSelectedControl(org.eclipse.swt.widgets.Control)" because the return value of "aero.minova.rcp.model.form.MDetail.getDetailAccessor()" is null

![grafik](https://user-images.githubusercontent.com/41451972/141974550-71226511-edb5-42d3-a0ba-ef1b63d208e6.png)

**Comment by janiak-minova** [comment]
Can you describe how to reproduce this error?

**Comment by DvonHolten** [comment]
goto 'werkzeuge' - Auftragsdefinition, then click the yellow field tJobDefiition.KeyText
seems always reproducible

**Comment by janiak-minova** [comment]
Sadly the error still doesn't occur for me. 
I think the underlying problem is either, that you are using an older Version of the application, or that your "Auftragsdefinition"-Mask is broken. You could try deleting your workspace-folder (in the preferences) and opening "Auftragsdefinition" again to see if that helps.

<img width="716" alt="Bildschirmfoto 2021-11-16 um 13 58 56" src="https://user-images.githubusercontent.com/77741125/141991958-6e210dfb-1134-4f0f-9250-e02b5fbce81a.png">

 You could also try to see if pull request #1016 solves your issue.

**Comment by janiak-minova** [comment]
Ich schließe das Issue, falls der Fehler erneut auftritt einfach wieder öffnen oder ein neues Issue anlegen.
