### ISSUE TITLE
Portierung auf Java 17

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#847]
Wir müssen auf Java 17 portieren, da das aktuell die neuste Longterm-Version ist.

**Comment by CE7** [comment]
Wir werden dafür das Plugin für die Generierung  von Java-Klassen anpassen müssen. Dies funktioniert aktuell nicht mehr mit Java 16

**Comment by janiak-minova** [comment]
Außerdem sollte das Encodieren von Nutzername und Passwort beim Authentifizieren beim CAS auf UTF-8 umgestellt werden, damit mehr Sonderzeichen unterstützt werden (siehe auch #743).

**Comment by vogella** [comment]
Fehler beim Build mit Java 16 (und wahrscheinlich auch mit Java 17).

ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (xjc) on project aero.minova.rcp.form.setup: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

**Comment by splitcells** [comment]
@janiak-minova Können wir dieses Projekt aus dem Oiltanking-Projekt entfernen?
So wie ich es verstehe, haben wir einen gewissen Zeitdruck.
